version: '3'
services:
  proxy:
      build: ./nginx2
      ports:
          - "80:80"
      volumes:
       - ./templates:/usr/share/nginx/html/static
      depends_on:
        - app_comp
    
  
  app_comp:
    image: 644435390668.dkr.ecr.eu-west-3.amazonaws.com/freedivingcompetitions:${VERSION_COMP}
    # environment:
    #   APP_PORT: "80"
    # ports:
    #   - "5001:5000"
    depends_on:
      my_db:
        condition: service_healthy 

  my_db:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DATABASE: global
    ports:
      - "27017:27017" 
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval","db.runCommand({ping:1}).ok"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  data:
    driver: local

# networks:
#   default:
#     name: ${NETWORK}
#     external: true